name: MoreCommands
main: GlaciercreepsMC\morecommands\MoreCommands
version: 1.0.2
api: [1.0.0, 1.1.0]
description: Adds more commands for moderators and admins
commands:
    gms:
        usage: /gms
        description: Changes gamemode to survival
        default: op
    gmc:
        usage: /gmc
        description: Changes gamemode to creative
        default: op
    gma:
        usage: /gma
        description: Changes gamemode to adventure
        default: op
    gmspc:
        usage: /gmspc
        description: Changes gamemode to spectator
        default: op
    heal:
        usage: /heal [player]
        description: Heals you or a specified player
        default: op
