name: MoreCommands
main: GlaciercreepsMC\morecommands\MoreCommands
version: 1.0.2
api: [1.0.0, 1.1.0]
description: Adds more commands for moderators and admins
commands:
    gms:
        usage: /gms
        description: Changes gamemode to survival
        default: op
    gmc:
        usage: /gmc
        description: Changes gamemode to creative
        default: op
    gma:
        usage: /gma
        description: Changes gamemode to adventure
        default: op
    gmspc:
        usage: /gmspc
        description: Chagnes gamemode to spectator
        default: op
    mute:
        usage: /mute <player>
        description: Mutes a player
        default: op
    unmute:
        usage: /unmute <player>
        description: Unmutes a player
        default: op
permissions:
    morecommands.mute:
        default: op
        description: Allows you to mute other players
    morecommands.unmute:
        default: op
        description: Allows you to unmute muted players
